### ISSUE TITLE
[Rank A BUG] monorail doesn't show changes after staging the file

### ISSUE THREAD

**Issue by neopug** [pnordahl/monorail#20]
**Monorail version**: `monorail 3.1.0`
**OS**: `macOS 14.7 (23H124) (Sonoma)`
**Git**: `git version 2.39.5 (Apple Git-154)`
**Description**: Monorail doesn't show changes after staging the files (monorail analysis has no targets).
**The way to reproduce**:
### Prereq:
```
git init monorail-tutorial
cd monorail-tutorial
mkdir shell
echo "date" > shell/test.sh
chmod +x shell/test.sh
cat <<EOF > Monorail.json
{
  "targets": [
    { "path": "shell" }
  ]
}
EOF
```
### Check
```
> monorail analyze --changes
{"timestamp":"2024-11-02T20:06:10.440414+00:00","changes":[{"path":"Monorail.json"},{"path":"shell/test.sh"}],"targets":["shell"]}
> git add shell/test.sh
> monorail analyze --changes
{"timestamp":"2024-11-02T20:06:37.918368+00:00","changes":[{"path":"Monorail.json"}],"targets":[]}
```
### Desired behavior
Monorail needs to show targets even if the file was staged

**Comment by pnordahl** [comment]
Taking a look, thanks for the report!

**Comment by pnordahl** [comment]
Resolved in https://github.com/pnordahl/monorail/pull/21 and merged.
